### ISSUE TITLE
Aniversário deveria ser do tipo date e não datetime.

### ISSUE THREAD

**Issue by ooredroxoo** [juntossomosmais/code-challenge#1]
## Sugestão
Estou analisando o README e pensando em como vou modelar os dados dentro da aplicação, quando me deparei com a data de aniversário (** birthday**) exibida no output:

```json
{
    "outros" : "dados omitidos para brevidade",
    "birthday": "1979-01-22T03:35:31Z",
}
```

Visto que a menos que alguém tenha interesse no cadastro de um mapa astral a informação de horário não seria muito útil, sendo em um cenário real, mas lógico para este campo gravar apenas a data, isso faz ainda mais sentido para pessoas que nem se quer sabem em que momento nasceram.

**Comment by willianantunes** [comment]
Oi @ooredroxoo! O desafio, além disso, tem outras provocações também. O como é implementado e dúvidas devem ser direcionadas ao e-mail que colocamos no [README.md](https://github.com/juntossomosmais/code-challenge/blob/2fff3622909d37cb7da9572b401b4e819d80c99c/README.md#como-entregar). Obrigado!
