### ISSUE TITLE
[Dúvida]: Classificação dos tipos de clientes

### ISSUE THREAD

**Issue by luanascardua** [juntossomosmais/code-challenge#4]
Sobre as regras de negócio para classificar os tipos de clientes. No readme possui 4 (bounding box) para classificar de acordo com os rótulos, porém esse está sem rótulo, qual seria?
```
minlon: -19.766959
minlat -52.997614
maxlon: -23.966413
maxlat: -44.428305
```

**Comment by willianantunes** [comment]
Oi @luanascardua. Este está dentro do rótulo `ESPECIAL`.

**Comment by luanascardua** [comment]
obrigada!
